// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnMraylZe2yYI1KN3DDKB-_ajyS1nD8c',
    appId: '1:612234204721:android:4918670d725495dd492710',
    messagingSenderId: '612234204721',
    projectId: 'cobonno-prod',
    storageBucket: 'cobonno-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvG6pcQT0MEFdPJ72toGzfvaYZhvJhfew',
    appId: '1:612234204721:ios:aefd6a8bd3e68701492710',
    messagingSenderId: '612234204721',
    projectId: 'cobonno-prod',
    storageBucket: 'cobonno-prod.appspot.com',
    androidClientId: '612234204721-23ng918fv05lrlto0tjquafsmdqsm2uc.apps.googleusercontent.com',
    iosClientId: '612234204721-ue2celmh38k0n5i3oe72csila69154k8.apps.googleusercontent.com',
    iosBundleId: 'com.cobonno.app',
  );
}
